name: Convert to ADG rule

on:
  schedule:
    - cron: '0 1 * * *' 
  workflow_dispatch:

jobs:
  modify-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Modify ADs_merged.txt
        run: |
          curl -skL https://raw.githubusercontent.com/wuiiled/Wuiiled_Setup/refs/heads/mihomo/rules/ADs_merged.txt | sed 's/DOMAIN-SUFFIX,/||/g; s/$/^/' >ADs_merged_adg.txt
          curl -skL https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/category-httpdns-cn.list | sed 's/+./||/g; s/$/^/' >Httpdns_adg.txt
          curl -skL https://raw.githubusercontent.com/wuiiled/PCDN-mihomo-list/refs/heads/main/pcdn.list | sed '/DOMAIN-REGEX,/d; sed '/^#/d'; s/DOMAIN-SUFFIX,/||/g; s/DOMAIN,/||/g; s/$/^/' > PCDN_adg.txt


      - name: Commit and push changes
        run: |
          mv {ADs_merged_adg.txt,Httpdns_adg.txt,PCDN_adg.txt} rules/
          CURRENT_TIME=$(date +"%Y-%m-%d %H:%M")
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git checkout --orphan adg
          git rm -rf .
          git add rules/*
          git commit -m "Auto Update $CURRENT_TIME"
          git push -f origin adg

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 2
